### ISSUE TITLE
Update to Stripe's new API (currently using deprecated)

### ISSUE THREAD

**Issue by igoragatti** [wpswings/subscriptions-for-woocommerce#179]
We have been having issues due to Stripe API deprecation.

When using Stripe's deprecated API we receive incomplete information in Stripe.

When using payment-intents (the new API) we receive complete information.

https://stripe.com/docs/payments/payment-intents

Note that this only happens on the recurrence. When the transactions come straight from Woocommerce it already uses the current Stripe API and not the deprecated API.

**Comment by WP-Swings** [comment]
Hi @igoragatti 

As You Mention Stripe New API ( currently Using deprecated) but we like to inform you that issue is already resolved from our end and currently stripe is working properly with the  plugin.
We appreciate for your observation and putting your suggestions.
We always welcome suggestions from everyone.
Regards
Wp Swings
