### ISSUE TITLE
Renewal orders that do not need processing are not transitioned to completed such as virtual downloadable products

### ISSUE THREAD

**Issue by Olsm** [wpswings/subscriptions-for-woocommerce#223]
You are adding the wps renewal order status into this filter: woocommerce_valid_order_statuses_for_payment_complete

You are using the name 'wps_renewal' here but the correct name of the order status is actually 'wc-wps_renewal'

I believe this causes the renewal order status not to be seen by WooCommerce as a valid order status to get transitioned to complete so the WC_Order->payment_complete() function does not transition the status to 'completed' instead of 'processing'.¨

This error does not only exist in wpswings subscriptions for woocommerce, but also in the paid add-on subscriptions for woocommerce pro.

I have described this as well in an email to support.

![bilde](https://github.com/wpswings/subscriptions-for-woocommerce/assets/8917803/1c5a1d42-bbf1-430d-bde4-e052e77cf2d8)

**Comment by WP-Swings** [comment]
Hi Olsm,
Thank you so much for your kind review of our plugin. We truly appreciate your feedback and are grateful for your support. Regarding your query, we have prepared a response for you.

"If the admin is selling a physical product as a subscription, it is not considered good practice to change the renewal order status to completed. That's why we are using the default functionality of WooCommerce, which works like this: if the order contains a virtual or downloadable product, the renewal order will be marked as completed. Otherwise, if the order contains a physical product, it will be marked as processing once payment is done. For example, if the admin is selling a packet of bread as a subscription product (which is a physical product), every renewal order needs to be marked as processing because it contains a physical product. Thank you for your suggestion regarding the status standard. We have taken note of it and will check and implement it in our plugin accordingly."
Best Regards

**Comment by Olsm** [comment]
Hi there.

What you have explained now is the same that I have been telling you, this is how the plugins should work. However, because of a bug in your code, this does **not** happen: "if the order contains a virtual or downloadable product, the renewal order will be marked as completed". 

Regarding this: "Thank you for your suggestion regarding the status standard. We have taken note of it and will check and implement it in our plugin accordingly."

No, I never suggested a status standard, setting or implementation. I have told you that it does not work and not only that, you have seen it on my website that a PayPal renewal order ended up in status "processing" instead of "completed" when the product only consist of a virtual downloadable product. I am asking for this issue to be solved and I have shown you how I believe it can be solved. 

I have explained the issue above and created a pull request with a suggestion for how to solve it. Please have your developers look at this and solve it. They can test the changes in my pull request and approve and merge it if it fixes the issue.

**Comment by WP-Swings** [comment]
Hi Olsm,
Thank you for your response. We have made modifications to the plugin code so that it now checks if a renewal order contains a virtual downloadable product. If it does, the plugin will automatically change the order status to completed from PayPal renewal. We will address this issue in the next version update of our plugin.
Best Regard
WP Swings
